import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ta_IN': {
      'fuel': 'எரிபொருள்',
      'vehicle': 'வாகனம்',
      'choose_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',

      "monthly_based_graph": "மாதாந்திர அடிப்படையிலான வரைபடம்",
      "sales": "விற்பனை",
      "expenses": "செலவுகள்",
      "no_finance_data": "நிதி தரவு இல்லை",
      "guidelines": "வழிகாட்டுதல்கள்",
      "view_all": "அனைத்தும்",
      "no_guidelines": "வழிகாட்டுதல்கள் இல்லை",
      "unable_to_open_content": "உள்ளடக்கத்தை திறக்க முடியவில்லை",
      "market_prices": "அருகிலுள்ள சந்தை விலைகள்",
      "no_data_available": "தரவு இல்லை",
      "error_message": "பிழை: {error}",
      "trending_crops": "பிரபலமான பயிர்கள்",
      "tasks": "பணிகள்",
      "no_tasks_available": "பணிகள் இல்லை",
      "widget_settings": "விட்ஜெட் அமைப்புகள்",
      "weather_payments": "வானிலை & பணம் செலுத்துதல்",
      "finance_graph": "நிதி வரைபடம்",
      "cancel": "ரத்து செய்",
      "save": "சேமி",
      "receivables": "பெறத்தக்கவை",
      "payables": "செலுத்த வேண்டியவை",
      "humidity_percentage": "ஈரப்பதம்: ",
      "currency_symbol": "₹",
    },
    'hi_IN': {
      'fuel': 'ईंधन',
      'vehicle': 'वाहन',
      'choose_language': 'भाषा चुनें',
      "monthly_based_graph": "मासिक आधारित ग्राफ",
      "sales": "बिक्री",
      "expenses": "खर्च",
      "no_finance_data": "कोई वित्त डेटा उपलब्ध नहीं",
      "guidelines": "दिशानिर्देश",
      "view_all": "सभी",
      "no_guidelines": "कोई दिशानिर्देश उपलब्ध नहीं",
      "unable_to_open_content": "सामग्री खोलने में असमर्थ",
      "market_prices": "आस-पास के बाजार के दाम",
      "no_data_available": "कोई डेटा उपलब्ध नहीं",
      "error_message": "त्रुटि: {error}",
      "trending_crops": "लोकप्रिय फसलें",
      "tasks": "कार्य",
      "no_tasks_available": "कोई कार्य उपलब्ध नहीं",
      "widget_settings": "विजेट सेटिंग्स",
      "weather_payments": "मौसम और भुगतान",
      "finance_graph": "वित्त ग्राफ",
      "cancel": "रद्द करें",
      "save": "सहेजें",
      "receivables": "प्राप्य",
      "payables": "देय",
      "humidity_percentage": "नमी: ",
      "currency_symbol": "₹",
    },
    'en_US': {
      "monthly_based_graph": "Monthly Based Graph",
      "sales": "Sales",
      "land_vs_crop": "Land vs Crop",
      "expenses": "Expenses",
      "no_finance_data": "No finance data available",
      "guidelines": "Guidelines",
      "view_all": "All",
      "no_guidelines": "No guidelines available",
      "unable_to_open_content": "Unable to open guideline content",
      "market_prices": "Near-By Market Prices",
      "no_data_available": "No data available",
      "error_message": "Error: {error}",
      "trending_crops": "Trending Crops",
      "tasks": "Tasks",
      "no_tasks_available": "No tasks available",
      "widget_settings": "Widget Settings",
      "weather_payments": "Weather & Payments",
      "finance_graph": "Finance Graph",
      "cancel": "Cancel",
      "save": "Save",
      "receivables": "Receivables",
      "payables": "Payables",
      "humidity_percentage": "Humidity:",
      "currency_symbol": "₹",
      'choose_language': 'Choose Language',
      'cropOverview': 'Crop Overview',
      'cropDetails': 'Crop Details',
      'editCrop': 'Edit Crop',
// Add these to your localization file
'schedules': 'Schedules',
'schedule_details': 'Schedule Details',
'search_schedules': 'Search schedules...',
'activity_type': 'Activity Type',
'days': 'Days',
'description': 'Description',
'add_schedule': 'Add Schedule',
'failed_to_load_schedules': 'Failed to load schedules',
'failed_to_load_schedule_details': 'Failed to load schedule details',
'no_schedules_found': 'No schedules found',
////

      'nextHarvest': 'The next harvesting day is in @days days.',

      'addNewTask': 'Add New Task +',
      'cropType': 'Crop Type',
      'harvestFrequency': 'Harvest Frequency',
      'plantationDate': 'Plantation Date',
      'measurement': 'Measurement',
      'unit': 'Unit',
      'surveyDetails': 'Survey Details',
      'location': 'Location',
      'pattaNumber': 'Patta Number',
      'update': 'Update',
      'Expenses': 'Expenses',
      'Total Expenses': 'Total Expenses',
      'week': 'week',
      '30days': '30 days',
      'year': 'year',
      'All': 'All',
      'Purchases': 'Purchases',
      'No transactions found': 'No transactions found',
      'Add New Expenses': 'Add New Expenses',
      'Purchase': 'Purchase',
      'Crop*': 'Crop*',
      'Date*': 'Date*',
      'Type of Expense*': 'Type of Expense*',
      'Amount*': 'Amount*',
      'Upload Documents (Optional)': 'Upload Documents (Optional)',
      'Save': 'Save',
      'Please select a date': 'Please select a date',
      'Please select an expense type': 'Please select an expense type',
      'Please enter an amount': 'Please enter an amount',
      'Please enter a valid amount': 'Please enter a valid amount',
      'vendor_customer': 'Vendors/Customers',
      'both': 'Both',
      'customer': 'Customer',
      'vendor': 'Vendor',
      'add_new': 'Add New',
      'add_customer': 'Add Customer',
      'add_vendor': 'Add Vendor',
      'add_both': 'Add Both',
      'customer_name': 'Customer Name',
      'vendor_name': 'Vendor Name',
      'shop_name': 'Shop Name',
      'business_name': 'Business Name',
      'mobile_number': 'Mobile Number',
      'email': 'Email',
      'door_no_street': 'Door No/Street',
      'pincode': 'Pincode',
      'gst_number': 'GST Number',
      'tax_number': 'Tax Number',
      'opening_balance': 'Total Outstanding',
      'photo': 'Photo',
      'upload_photo': 'Upload Photo',
      'remove_photo': 'Remove Photo',
      'submit': 'Submit',
      'basic_info': 'Basic Information',
      'location_info': 'Location Information',
      'financial_info': 'Financial Information',
      'inventory_type': 'Inventory Type',
      'select_inventory_type': 'Select Inventory Type',
      'country': 'Country',
      'state': 'State',
      'city': 'City',
      'taluk': 'Taluk',
      'village': 'Village',
      'loading_countries': 'Loading countries...',
      'loading_states': 'Loading states...',
      'loading_cities': 'Loading cities...',
      'loading_taluks': 'Loading taluks...',
      'loading_villages': 'Loading villages...',
      'required_field': 'Required field',
      'invalid_phone': 'Invalid phone number',
      'invalid_email': 'Invalid email address',
      'pincode_length': 'Pincode must be 6 digits',
      'details_not_found': 'Details Not Found',
      'item_not_found': 'Item not found',
      'vendor_details': 'Vendor Details',
      'customer_details': 'Customer Details',
      'address': 'Address',
      'call': 'Call',
      'calling_number': 'Calling {number}',
      'edit': 'Edit',

      'subscription_usage': 'Subscription Usage',
      'hello': 'Hello',
      'current_subscription': 'Current Subscription',
      'land_limit': 'Land Limit',
      'crops_limit': 'Crops Limit',
      'view_subscription_plans': 'View Subscription Plans',
      'subscription_plans': 'Subscription Plans',
      'your_current_plan': 'Your Current Plan',
      'proceed_to_payment': 'Proceed to Payment',
      'no_packages_available': 'No packages available',
      'land_management': 'Land Management',
      'crops_management': 'Crops Management',
      'expense_tracking': 'Expense Tracking',
      'sales_tracking': 'Sales Tracking',
      'customer_management': 'Customer Management',
      'unlimited': 'Unlimited',
      'payment': 'Payment',
      'no_package_selected': 'No package selected',
      'selected_plan': 'Selected Plan',
      'payment_summary': 'Payment Summary',
      'plan_price': 'Plan Price',
      'discount': 'Discount',
      'total_amount': 'Total Amount',
      'payment_successful': 'Payment Successful',
      'payment_success_message':
          'You\'ve unlocked Platinum level. Explore Advanced Agricultural Features now!',
      'continue_to_dashboard': 'Continue to Dashboard',
      'payment_failed': 'Payment Failed',
      'payment_failed_message': 'Please try again or check your details...',
      'back': 'Back',
      'try_again': 'Try Again',
      'error': 'Error',
      'retry': 'Retry',
      'no_usage_data': 'No usage data available',
      'inventory.title': 'Inventory',
      'inventory.addItem': 'Add Item',
      'inventory.itemName': 'Item Name',
      'inventory.quantity': 'Quantity',
      'inventory.submit': 'Submit',
      'inventory.addAtLeastOne': 'Please add at least one item',
      'inventory.positiveNumber': 'Quantity must be positive',
      'inventory.validNumber': 'Please enter a valid number',
      'inventory.fuel': 'Fuel',
      'inventory.vehicle': 'Vehicle',
      'inventory.machinery': 'Machinery',
      'inventory.tools': 'Tools',
      'inventory.pesticides': 'Pesticides',
      'inventory.fertilizers': 'Fertilizers',
      'inventory.seeds': 'Seeds',
      'landManagement': 'Land Management',
      'landManagementDescription':
          'You can now Effectively Manage Your Land & Crop Resources & Agricultural Operations.',
      'schedule': 'Schedule',
      'scheduleDescription':
          'You can Create & Assign Tasks Related to Plowing, Sowing, Harvesting etc.',
      'costManagement': 'Cost Management',
      'costManagementDescription':
          'Categorize & Manage your Expenses in Day-to-Day basis.',
      'letsStart': 'Let\'s Start',
      "no_internet_title": "No Internet Connection",
      "no_internet_message": "Please check your network settings",
      "ok_button": "OK",
      "connection_lost_title": "Connection Lost",
      "connection_lost_message": "You're offline. Some features may not work",
      "connection_restored_title": "Back Online",
      "connection_restored_message": "Internet connection restored",
      "connection_error_title": "Connection Error",
      "connection_error_message": "Failed to check network status",
      //
      'guidelines_title': 'Implementation Guide',
      'search_placeholder': 'Search',
      'select_crop': 'Select Crop',
      'select_category': 'Select Category',
      'no_guidelines_found': 'No guidelines found',
      ...enU,
      'inventory': 'Inventory',
      'no_inventory_data': 'No inventory data available',
      'add_inventory': 'Add Inventory',
      'fuel': 'Fuel',
      'vehicle': 'Vehicle',
      'machinery': 'Machinery',
      'tools': 'Tools',
      'pesticides': 'Pesticides',
      'fertilizers': 'Fertilizers',
      'seeds': 'Seeds',
      'add_item': 'Add @category',
      'quantity': 'Quantity',
      'enter_quantity': 'Enter quantity',

      'item_added_successfully': 'Item added successfully',
      ...fuel, ...sales,
      'select_markets': 'Select Markets',
      'search_markets': 'Search markets...',
      'clear_all': 'Clear All',
      'select_all': 'Select All',
      'confirm': 'Confirm',
      'no_markets_selected': 'No markets selected',
      'markets_selected': 'markets selected',
      'no_markets_found': 'No markets found',
      'Consumption': 'Consumption',
      'Date': 'Date',
      'Crop': 'Crop',
      'Inventory Type': 'Inventory Type',
      'Inventory Category': 'Inventory Category',
      'Inventory Item': 'Inventory Item',
      'Quantity (Liter)': 'Quantity (Liter)',
      'Documents': 'Documents',
      'Document Category': 'Document Category',
      'New Document Category': 'New Document Category',
      'Upload Document': 'Upload Document',
      'Description': 'Description',
        'salesDetails': 'Sales Details',
      'newSales': 'New Sales Entry',
      'editSales': 'Edit Sales Entry',
      'addDeduction': 'Add Deduction',
      'product': 'Product',
      'date': 'Date',
      'salesQuantity': 'Sales Quantity',
      'quantityAmount': 'Quantity Amount',
      'salesAmount': 'Sales Amount',
      'deductions': 'Deductions',
      'amountPaid': 'Amount Paid',
      'reasonForDeduction': 'Reason for Deduction',
      'deductionAmount': 'Deduction Amount',
      'addDeductionButton': 'Add Deduction',
      'grossSales': 'Gross Sales',
      'deduction': 'Deduction',
      'netSales': 'Net Sales',
      'uploadedDocuments': 'Uploaded Documents',
    },
  };

  Map<String, String> fuel = {
    // Common
    'Fuel': 'Fuel',
    'Date': 'Date',
    'Vendor': 'Vendor',
    'Description': 'Description',
    'Documents': 'Documents',
    'Add Document': 'Add Document',
    'Cancel': 'Cancel',
    'Delete': 'Delete',
    'Update': 'Update',
    'Add': 'Add',
    'Edit': 'Edit',
    'Confirm Delete': 'Confirm Delete',
    'Purchase Details': 'Purchase Details',
    'Add Purchase': 'Add Purchase',
    'Edit Purchase': 'Edit Purchase',

    // Validation messages
    'Please select a vendor': 'Please select a vendor',
    'Please select a fuel type': 'Please select a fuel type',
    'Please enter amount': 'Please enter amount',
    'Please enter a valid number': 'Please enter a valid number',
    'Please enter quantity': 'Please enter quantity',

    // Success messages
    'Fuel purchase added successfully': 'Fuel purchase added successfully',
    'Fuel purchase updated successfully': 'Fuel purchase updated successfully',
    'Fuel purchase deleted successfully': 'Fuel purchase deleted successfully',

    // Error messages
    'Failed to load fuel types': 'Failed to load fuel types',
    'Failed to load purchases': 'Failed to load purchases',
    'Failed to load purchase details': 'Failed to load purchase details',
    'Failed to add fuel purchase': 'Failed to add fuel purchase',
    'Failed to update fuel purchase': 'Failed to update fuel purchase',
    'Failed to delete fuel purchase': 'Failed to delete fuel purchase',
    'No fuel types available': 'No fuel types available',
    'No purchase selected': 'No purchase selected',

    // Form labels
    'Fuel Category': 'Fuel Category',
    'Purchase Amount': 'Purchase Amount',
    'Quantity (Litre)': 'Quantity (Litre)',
    'Are you sure you want to delete this purchase?':
        'Are you sure you want to delete this purchase?',
  };

  Map<String, String> enU = {
    'sales': 'Sales',
    'saleDetails': 'Sale Details',
    'newSale': 'New Sale',
    'editSale': 'Edit Sale',
    'product': 'Product',
    'date': 'Date',
    'customer': 'Customer',
    'quantity': 'Quantity',
    'unit': 'Unit',
    'amountPerUnit': 'Amount per unit',
    'grossSalesAmount': 'Gross Sales Amount',
    'deductions': 'Deductions',
    'netSalesAmount': 'Net Sales Amount',
    'amountPaid': 'Amount Paid',
    'description': 'Description',
    'addDeduction': 'Add Deduction',
    'reason': 'Reason',
    'percentage': 'Percentage',
    'deductionAmount': 'Deduction Amount',
    'currency': 'Currency',
    'customReason': 'Custom Reason',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'add': 'Add',
    'update': 'Update',
    'requiredField': 'This field is required',
    'invalidPercentage': 'Percentage must be between 0-100',
    'saleAdded': 'Sale added successfully',
    'saleUpdated': 'Sale updated successfully',
    'saleDeleted': 'Sale deleted successfully',
    'errorLoadingSales': 'Error loading sales',
    'errorLoadingDetails': 'Error loading sale details',
    'errorSubmittingForm': 'Error submitting form',
    'noSalesFound': 'No sales found',
    'noDetailsFound': 'Sale details not found',
    'noDeductions': 'No deductions added',
    'documents': 'Documents',
  };
  // lib/app/modules/inventory/fuel/localization/en_US.dart
  Map<String, String> sales = {
    'sales_details': 'Sales Details',
    'edit_sales': 'Edit Sales',
    'new_sales': 'New Sales',
    'date': 'Date',
    'customer': 'Customer',
    'quantity': 'Quantity',
    'unit': 'Unit',
    'price_per_unit': 'Price per Unit',
    'amount_paid': 'Amount Paid',
    'deductions': 'Deductions',
    'documents': 'Documents',
    'description': 'Description',
    'submit': 'Submit',
    'update': 'Update',
    'add_deduction': 'Add Deduction',
    'cancel': 'Cancel',
    'add': 'Add',
    'type': 'Type',
    'fixed': 'Fixed',
    'percentage': 'Percentage',
    'enter_reason': 'Please enter reason',
    'enter_amount': 'Please enter amount',
    'select_customer': 'Please select customer',
    'enter_quantity': 'Please enter quantity',
    'select_unit': 'Please select unit',
    'enter_price': 'Please enter price',
    'gross_sales': 'Gross Sales',
    'deduction': 'Deduction',
    'net_sales': 'Net Sales',
    'uploaded_documents': 'Uploaded Documents',
    'custom': 'Custom',
    'custom_reason': 'Custom Reason',
    'reason': 'Reason',
    'amount': 'Amount',
  };
  Map<String, String> enUS = {
    // General
    'sales': 'Sales',
    'product': 'Product',
    'customer': 'Customer',
    'date': 'Date',
    'description': 'Description',
    'submit': 'Submit',
    'update': 'Update',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm_delete': 'Confirm Delete',
    'are_you_sure_delete': 'Are you sure you want to delete this sale?',
    'cancel': 'Cancel',
    'success': 'Success',
    'error': 'Error',
    'loading': 'Loading...',
    'required_field': 'This field is required',

    // Sales List Screen
    'total_sales': 'Total Sales',
    'last_30_days': 'Last 30 Days',

    // Sales Details Screen
    'sale_details': 'Sale Details',
    'gross_sales': 'Gross Sales',
    'deduction': 'Deduction',
    'net_sales': 'Net Sales',
    'amount_paid': 'Amount Paid',
    'uploaded_documents': 'Uploaded Documents',
    'bill': 'Bill',
    'receipt': 'Receipt',

    // Sales Form Screen (New/Edit)
    'new_sale': 'New Sale',
    'edit_sale': 'Edit Sale',
    'add_customer': 'Add Customer',
    'quantity': 'Quantity',
    'unit': 'Unit',
    'amount_per_unit': 'Amount per Unit',
    'total': 'Total',
    'deductions': 'Deductions',
    'add_deduction': 'Add Deduction',
    'upload_bill': 'Upload Bill',
    'upload_receipt': 'Upload Receipt',
    'sale_added_success': 'Sale added successfully!',
    'sale_updated_success': 'Sale updated successfully!',
    'sale_deleted_success': 'Sale deleted successfully!',

    // Add Deduction Popup
    'reason': 'Reason',
    'percentage': 'Percentage (%)',
    'deduction_amount': 'Deduction Amount',
  };
}
