name: argiot
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl: ^0.20.2
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  loading_animation_widget: ^1.3.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.3.1
  geocoding: ^4.0.0
  connectivity_plus: ^6.1.4
  get_storage: ^2.1.1
  fluttertoast: ^8.2.12
  pin_code_fields: ^8.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  http: ^1.4.0
  file_picker: ^10.2.0
  flutter_pdfview: ^1.4.1+1
  image_picker: ^1.1.2
  syncfusion_flutter_charts: ^30.1.42
  table_calendar: ^3.2.0
  razorpay_flutter: ^1.4.0
  dropdown_button2: ^2.3.9
  pie_chart: ^5.4.0
  multi_select_flutter: ^4.1.3
  google_sign_in: ^6.3.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  font_awesome_flutter: ^10.9.1
  flutter_expandable_fab: ^2.5.2
  image: ^4.5.4
  fl_chart: ^1.1.0
  url_launcher: ^6.3.2
  home_widget: ^0.8.0
  mime: ^2.0.0
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/icon/svg/

