class English {
  static Map<String, String> list = {
    "consumption_purchase_title": "Consumption & Purchase",
    "inventory_category": "Inventory Category",
    "select_inventory_category": "Select Inventory Category",
    "inventory_item": "Inventory Item",
    "select_inventory_item": "Select Inventory Item",
    "consumption": "Consumption",
    "purchase": "Purchase",
    "select_item_to_view_data": "Please select an inventory item to view data",
    "no_consumption_records": "No consumption records found",
    "no_purchase_records": "No purchase records found",
    "failed_to_load_categories": "Failed to load categories",
    "failed_to_load_items": "Failed to load items",
    "failed_to_load_data": "Failed to load data",
    "no_records_found": "No records found for selected item",
    "monthly_based_graph": "Monthly Based Graph",
    "sales": "Sales",
    "land_vs_crop": "Land vs Crop",
    "expenses": "Expenses",
    "expense": "Expense",
    "no_finance_data": "No finance data available",
    "guidelines": "Guidelines",
    "view_all": "All",
    "no_guidelines": "No guidelines available",
    "unable_to_open_content": "Unable to open guideline content",
    "market_prices": "Near-By Market Prices",
    "no_data_available": "No data available",
    "error_message": "Error: {error}",
    "trending_crops": "Trending Crops",
    "tasks": "Tasks",
    "no_tasks_available": "No tasks available",
    "widget_settings": "Widget Settings",
    "weather_payments": "Weather & Payments",
    "finance_graph": "Finance Graph",
    "cancel": "Cancel",
    "save": "Save",
    "receivables": "Receivables",
    "payables": "Payables",
    "humidity_percentage": "Humidity:",
    "currency_symbol": "₹",
    "choose_language": "Choose Language",
    "cropOverview": "Crop Overview",
    "cropDetails": "Crop Details",
    "editCrop": "Edit Crop",
    "schedules": "Schedules",
    "schedule_details": "Schedule Details",
    "search_schedules": "Search schedules...",
    "activity_type": "Activity Type",
    "days": "Days",
    "description": "Description",
    "add_schedule": "Add Schedule",
    "failed_to_load_schedules": "Failed to load schedules",
    "failed_to_load_schedule_details": "Failed to load schedule details",
    "no_schedules_found": "No schedules found",
    "nextHarvest": "The next harvesting day is in @days days.",
    "addNewTask": "Add New Task +",
    "cropType": "Crop Type",
    "harvestFrequency": "Harvest Frequency",
    "plantationDate": "Plantation Date",
    "measurement": "Measurement",
    "unit": "Unit",
    "surveyDetails": "Survey Details",
    "location": "Location",
    "pattaNumber": "Patta Number",
    "update": "Update",
    "total_expenses": "Total Expenses",
    "week": "week",
    "30days": "30 days",
    "year": "year",
    "all": "All",
    "purchases": "Purchases",
    "No transactions found": "No transactions found",
    "Add New Expenses": "Add New Expenses",
    "Purchase": "Purchase",
    "Crop*": "Crop",
    "Date*": "Date",
    "Type of Expense": "Type of Expense",
    "Amount*": "Amount",
    "Upload Documents (Optional)": "Upload Documents (Optional)",
    "Save": "Save",
    "Please select a date": "Please select a date",
    "Please select an expense type": "Please select an expense type",
    "Please enter an amount": "Please enter an amount",
    "Please enter a valid amount": "Please enter a valid amount",
    "vendor_customer": "Vendors/Customers",
    "both": "Both",
    "customer": "Customer",
    "vendor": "Vendor",
    "add_new": "Add New",
    "add_customer": "Add Customer",
    "add_vendor": "Add Vendor",
    "add_both": "Add Both",
    "customer_name": "Customer Name",
    "vendor_name": "Vendor Name",
    "shop_name": "Shop Name",
    "business_name": "Business Name",
    "mobile_number": "Mobile Number",
    "email": "Email",
    "door_no_street": "Door No/Street",
    "pincode": "Pincode",
    "gst_number": "GST Number",
    "tax_number": "Tax Number",
    "opening_balance": "Total Outstanding",
    "photo": "Photo",
    "upload_photo": "Upload Photo",
    "remove_photo": "Remove Photo",
    "submit": "Submit",
    "basic_info": "Basic Information",
    "location_info": "Location Information",
    "financial_info": "Financial Information",
    "inventory_type": "Inventory Type",
    "select_inventory_type": "Select Inventory Type",
    "country": "Country",
    "state": "State",
    "city": "City",
    "taluk": "Taluk",
    "village": "Village",
    "loading_countries": "Loading countries...",
    "loading_states": "Loading states...",
    "loading_cities": "Loading cities...",
    "loading_taluks": "Loading taluks...",
    "loading_villages": "Loading villages...",
    "required_field": "Required field",
    "invalid_phone": "Invalid phone number",
    "invalid_email": "Invalid email address",
    "pincode_length": "Pincode must be 6 digits",
    "details_not_found": "Details Not Found",
    "item_not_found": "Item not found",
    "vendor_details": "Vendor Details",
    "customer_details": "Customer Details",
    "address": "Address",
    "call": "Call",
    "calling_number": "Calling {number}",
    "edit": "Edit",
    "subscription_usage": "Subscription Usage",
    "hello": "Hello",
    "current_subscription": "Current Subscription",
    "land_limit": "Land Limit",
    "crops_limit": "Crops Limit",
    "view_subscription_plans": "View Subscription Plans",
    "subscription_plans": "Subscription Plans",
    "your_current_plan": "Your Current Plan",
    "proceed_to_payment": "Proceed to Payment",
    "no_packages_available": "No packages available",
    "land_management": "Land Management",
    "crops_management": "Crops Management",
    "expense_tracking": "Expense Tracking",
    "sales_tracking": "Sales Tracking",
    "customer_management": "Customer Management",
    "unlimited": "Unlimited",
    "payment": "Payment",
    "no_package_selected": "No package selected",
    "selected_plan": "Selected Plan",
    "payment_summary": "Payment Summary",
    "plan_price": "Plan Price",
    "discount": "Discount",
    "total_amount": "Total Amount",
    "payment_successful": "Payment Successful",
    "payment_success_message":
        "You\"ve unlocked Platinum level. Explore Advanced Agricultural Features now!",
    "continue_to_dashboard": "Continue to Dashboard",
    "payment_failed": "Payment Failed",
    "payment_failed_message": "Please try again or check your details...",
    "back": "Back",
    "try_again": "Try Again",
    "error": "Error",
    "retry": "Retry",
    "no_usage_data": "No usage data available",
    "inventory.title": "Inventory",
    "inventory.addItem": "Add Item",
    "inventory.itemName": "Item Name",
    "inventory.quantity": "Quantity*",
    "inventory.submit": "Submit",
    "inventory.addAtLeastOne": "Please add at least one item",
    "inventory.positiveNumber": "Quantity must be positive",
    "inventory.validNumber": "Please enter a valid number",
    "inventory.fuel": "Fuel",
    "inventory.vehicle": "Vehicle",
    "inventory.machinery": "Machinery",
    "inventory.tools": "Tools",
    "inventory.pesticides": "Pesticides",
    "inventory.fertilizers": "Fertilizers",
    "inventory.seeds": "Seeds",
    "landManagement": "Land Management",
    "landManagementDescription":
        "You can now Effectively Manage Your Land & Crop Resources & Agricultural Operations.",
    "schedule": "Schedule",
    "scheduleDescription":
        "You can Create & Assign Tasks Related to Plowing, Sowing, Harvesting etc.",
    "costManagement": "Cost Management",
    "costManagementDescription":
        "Categorize & Manage your Expenses in Day-to-Day basis.",
    "letsStart": "Let\"s Start",
    "no_internet_title": "No Internet Connection",
    "no_internet_message": "Please check your network settings",
    "ok_button": "OK",
    "connection_lost_title": "Connection Lost",
    "connection_lost_message": "You're offline. Some features may not work",
    "connection_restored_title": "Back Online",
    "connection_restored_message": "Internet connection restored",
    "connection_error_title": "Connection Error",
    "connection_error_message": "Failed to check network status",
    "guidelines_title": "Implementation Guide",
    "search_placeholder": "Search",
    "select_crop": "Select Crop",
    "select_category": "Select Category",
    "no_guidelines_found": "No guidelines found",
    "inventory": "Inventory",
    "no_inventory_data": "No inventory data available",
    "add_inventory": "Add Inventory",
    "fuel": "Fuel",
    "vehicle": "Vehicle",
    "machinery": "Machinery",
    "tools": "Tools",
    "pesticides": "Pesticides",
    "fertilizers": "Fertilizers",
    "seeds": "Seeds",
    "add_item": "Add @category",
    "enter_quantity": "Enter quantity",
    "item_added_successfully": "Item added successfully",
    "select_markets": "Select Markets",
    "search_markets": "Search markets...",
    "clear_all": "Clear All",
    "select_all": "Select All",
    "confirm": "Confirm",
    "no_markets_selected": "No markets selected",
    "markets_selected": "markets selected",
    "no_markets_found": "No markets found",
    "Consumption": "Consumption",
    "Date": "Date",
    "Crop": "Crop",
    "Inventory Type": "Inventory Type",
    "Inventory Category": "Inventory Category",
    "Inventory Item": "Inventory Item",
    "Quantity (Liter)": "Quantity (Liter)",
    "Documents": "Documents",
    "Document Category": "Document Category",
    "New Document Category": "New Document Category",
    "Upload Document": "Upload Document",
    "Description": "Description",
    "salesDetails": "Sales Details",
    "newSales": "New Sales ",
    "editSales": "Edit Sales ",
    "addDeduction": "Add Deduction",
    "product": "Product",
    "date": "Date",
    "salesQuantity": "Sales Quantity",
    "quantityAmount": "Quantity Amount",
    "salesAmount": "Sales Amount",
    "deductions": "Deductions",
    "amountPaid": "Amount Paid",
    "reasonForDeduction": "Reason for Deduction",
    "deductionAmount": "Deduction Amount",
    "addDeductionButton": "Add Deduction",
    "grossSales": "Gross Sales",
    "deduction": "Deduction",
    "netSales": "Net Sales",
    "uploadedDocuments": "Uploaded Documents",
    "Fuel": "Fuel",
    "Vendor": "Vendor",
    "Add Document": "Add Document",
    "Cancel": "Cancel",
    "Delete": "Delete",
    "Update": "Update",
    "Add": "Add",
    "Edit": "Edit",
    "Confirm Delete": "Confirm Delete",
    "Purchase Details": "Purchase Details",
    "Add Purchase": "Add Purchase",
    "Edit Purchase": "Edit Purchase",
    "fuel_entry": "Fuel",
    "select_date": "Select Date",
    "fuel_category": "Fuel Category",
    "purchase_amount": "Purchase Amount",
    "litre": "Litre",
    "upload_documents": "Upload Documents",
    "add": "Add",
    "gallery": "Gallery",
    "camera": "Camera",
    "files": "Files",
    "date_required": "Date is required",
    "fuel_category_required": "Fuel category is required",
    "vendor_required": "Vendor is required",
    "purchase_amount_required": "Purchase amount is required",
    "purchase_amount_invalid": "Enter a valid amount",
    "litre_required": "Litre is required",
    "litre_invalid": "Enter a valid quantity",
    "fuel_added_success": "Fuel added successfully!",
    "error_occurred": "An error occurred",
    "network_error": "Network error, please try again",
    "Please select a vendor": "Please select a vendor",
    "Please select a fuel type": "Please select a fuel type",
    "Please enter amount": "Please enter amount",
    "Please enter a valid number": "Please enter a valid number",
    "Please enter quantity": "Please enter quantity",
    "Fuel purchase added successfully": "Fuel purchase added successfully",
    "Fuel purchase updated successfully": "Fuel purchase updated successfully",
    "Fuel purchase deleted successfully": "Fuel purchase deleted successfully",
    "Failed to load fuel types": "Failed to load fuel types",
    "Failed to load purchases": "Failed to load purchases",
    "Failed to load purchase details": "Failed to load purchase details",
    "Failed to add fuel purchase": "Failed to add fuel purchase",
    "Failed to update fuel purchase": "Failed to update fuel purchase",
    "Failed to delete fuel purchase": "Failed to delete fuel purchase",
    "No fuel types available": "No fuel types available",
    "No purchase selected": "No purchase selected",
    "Fuel Category": "Fuel Category",
    "Purchase Amount": "Purchase Amount",
    "Quantity (Litre)": "Quantity (Litre)",
    "Are you sure you want to delete this purchase?":
        "Are you sure you want to delete this purchase?",
    "title": "Machinery",
    "category_required": "Category is required",
    "item_required": "Item is required",
    "type": "Type",
    "manual": "Manual",
    "fuel_capacity": "Fuel Capacity",
    "amount_required": "Amount is required",
    "amount_valid": "Enter a valid amount",
    "warranty_start": "Warranty Start Date",
    "warranty_end": "Warranty End Date",
    "warranty_end_after_start": "End date must be after start date",
    "add_button": "Add",
    "success_message": "Machinery added successfully!",
    "vehicle_screen_title": "Vehicle",
    "date_label": "Date",
    "inventory_category_label": "Inventory Category",
    "inventory_item_label": "Inventory Item",
    "vendor_label": "Vendor",
    "reg_no_label": "Reg No",
    "owner_name_label": "Owner Name",
    "date_of_reg_label": "Date of Reg",
    "reg_valid_till_label": "Reg Valid Till",
    "engine_no_label": "Engine No",
    "chasis_no_label": "Chasis No",
    "paid_amount": "Paid Amount",
    "running_km_label": "Running KM",
    "service_frequency_label": "Service Frequency",
    "unit_label": "Unit",
    "fuel_capacity_label": "Fuel Capacity (in Litres)",
    "average_mileage_label": "Average Mileage",
    "purchase_amount_label": "Purchase Amount",
    "upload_documents_label": "Upload Documents",
    "description_label": "Description",
    "insurance_details_label": "Insurance Details",
    "insurance_details_section": "Insurance Details",
    "company_name_label": "Company Name",
    "insurance_no_label": "Insurance No",
    "insurance_amount_label": "Insurance Amount",
    "start_date_label": "Start Date",
    "end_date_label": "End Date",
    "renewal_date_label": "Renewal Date",
    "fertilizer_entry_title": "Fertilizer",
    "category_label": "Category",
    "item_label": "Item",
    "date_hint": "Select date",
    "vendor_hint": "Select vendor",
    "quantity_label": "Quantity",
    "quantity_hint": "Enter quantity",
    "purchase_amount_hint": "Enter amount",
    "description_hint": "Add notes (optional)",
    "quantity_required": "Quantity is required",
    "quantity_invalid": "Quantity must be greater than 0",
    "amount_invalid": "Amount must be greater than 0",
    "fertilizer_add_success": "Fertilizer added successfully!",
    "fertilizer_add_failed": "Failed to add fertilizer",
    "fuel_inventory": "Fuel Inventory",
    "quantity": "Quantity",
    "uploaded_documents": "Uploaded Documents",
    "no_documents_available": "No documents available",
    "confirm_delete": "Confirm Delete",
    "delete_fuel_confirmation":
        "Are you sure you want to delete this fuel inventory?",
    "delete": "Delete",
    "error_loading_data": "Error loading data",
    "saleDetails": "Sale Details",
    "newSale": "New Sale",
    "editSale": "Edit Sale",
    "amountPerUnit": "Amount per unit",
    "grossSalesAmount": "Gross Sales Amount",
    "netSalesAmount": "Net Sales Amount",
    "reason": "Reason",
    "percentage": "Percentage",
    "currency": "Currency",
    "customReason": "Custom Reason",
    "requiredField": "This field is required",
    "invalidPercentage": "Percentage must be between 0-100",
    "saleAdded": "Sale added successfully",
    "saleUpdated": "Sale updated successfully",
    "saleDeleted": "Sale deleted successfully",
    "errorLoadingSales": "Error loading sales",
    "errorLoadingDetails": "Error loading sale details",
    "errorSubmittingForm": "Error submitting form",
    "noSalesFound": "No sales found",
    "noDetailsFound": "Sale details not found",
    "noDeductions": "No deductions added",
    "documents": "Documents",
    "sales_details": "Sales Details",
    "edit_sales": "Edit Sales",
    "new_sales": "New Sales",
    "price_per_unit": "Price per Unit",
    "amount_paid": "Amount Paid",
    "add_deduction": "Add Deduction",
    "fixed": "Fixed",
    "enter_reason": "Please enter reason",
    "enter_amount": "Please enter amount",
    "select_customer": "Please select customer",
    "select_unit": "Please select unit",
    "enter_price": "Please enter price",
    "gross_sales": "Gross Sales",
    "net_sales": "Net Sales",
    "custom": "Custom",
    "custom_reason": "Custom Reason",
    "amount": "Amount",
    "payables_receivables": "Payables & Receivables",
    "no_data": "No data found",
    "total": "Total",
    "paid": "Paid",
    "to_pay": "To Pay",
    "to_receive": "To Receive",
    "history": "History",
    "add_payment": "Add Payment",
    "sales_date": "Sales Date",
    "crop_name": "Crop Name",
    "add_payable": "Add Payable to @name",
    "add_receivable": "Add Receivable from @name",
    "current_payable": "Current Payable: ₹@amount",
    "current_receivable": "Current Receivable: ₹@amount",
    "payment_amount": "Payment Amount",
    "upload_document": "Upload Document",
    "document": "Document",
    "fill_required_fields": "Please fill all required fields",
    "no_payables_found": "No payables found",
    "shop": "Shop",
    "business": "Business",
    "unknown": "Unknown",
    "no_receivables_found": "No receivables found",
    "payables_history": "Payables History",
    "receivables_history": "Receivables History",
    "no_history_found": "No history found",
    "no_detail_found": "No detail found",
    "payable_detail": "Payable Detail",
    "receivable_detail": "Receivable Detail",
    "balance": "Balance",
    "received": "Received",
    "total_paid": "Total Paid",
    "total_received": "Total Received",
    "close": "Close",
    "vendor_payables": "Vendor Payables",
    "vendor_receivables": "Vendor Receivables",
    "no_vendor_payables": "No vendor payables found.",
    "no_vendor_receivables": "No vendor receivables found.",
    "seed": "Seed",
    "pesticide": "Pesticide",
    "fertilizer": "Fertilizer",
    "tool": "Tool",

    "add_vendor_payable": "Add Vendor Payable",
    "add_vendor_receivable": "Add Vendor Receivable",
    "all_fields_required": "All fields are required",
    "dd_mm_yyyy": "DD-MM-YYYY",
    "payable_history": "Payable History",
    "receivable_history": "Receivable History",
    "no_payables_history": "No payables history found.",
    "no_receivables_history": "No receivables history found.",
    "paid_date": "Paid Date",
    "received_date": "Received Date",
    "history_details": "History Details",
    "customer_vendor_details": "Customer & Vendor Details",
    "customer_receivables": "Customer Receivables",
    "customer_payables": "Customer Payables",
    "fuel_purchase": "Fuel Purchase",
    "fuel_purchase_payable": "Fuel Purchase (Payable)",
    "seed_purchase": "Seed Purchase",
    "fertilizer_purchase": "Fertilizer Purchase",
    "pesticide_purchase": "Pesticide Purchase",
    "vehicle_purchase": "Vehicle Purchase",
    "machinery_purchase": "Machinery Purchase",
    "tool_purchase": "Tool Purchase",
    "customer_payables_history": "Customer Payables History",
    "customer_receivables_history": "Customer Receivables History",
    "notifications": "Notifications",
    "this_notification_is_already_read": "This notification is already read.",
    "edit_task": "Edit Task",
    "add_new_task": "Add New Task",
    "crop": "Crop",
    "schedule_date": "Schedule Date",
    "recurring_task": "Recurring Task",
    "daily": "Daily",
    "weekly": "Weekly ",
    "monthly": "Monthly ",
    "mon": "Mon",
    "tue": "Tue",
    "wed": "Wed",
    "thu": "Thu",
    "fri": "Fri",
    "sat": "Sat",
    "sun": "Sun",
    "schedule_end_date": "Schedule End Date",
    "not_selected": "Not selected",
    "please_add_end_date": "Please add End Date",
    "update_task": "Update Task",
    "add_task": "Add Task",
    "reason_for_deduction": "Reason for Deduction",
    "please_enter_a_reason": "Please enter a reason",
    "deduction_amount": "Deduction Amount",
    "please_enter_deduction_amount": "Please enter deduction amount",
    "deduction_must_be_greater_than_0": "Deduction must be greater than 0",
    "percentage_cannot_exceed_100": "Percentage cannot exceed 100%",
    "no_documents_added": "No documents added",

    "sales_list": "Sales List",
    "total_sales": "Total Sales",
    "add_document": "Add Document",
    "select_document_type": "Select Document type",
    "enter_document_type": "Enter Document type",
    "please_enter_a_document": "Please enter a document",
    "month": "month",
    "sale_quantity": "Sale Quantity ",
    "sales_amount": "Sales Amount",
    "total_sales_amount": "Total Sales Amount",
    "please_select_a_customer": "Please select a customer",
    "sales_quantity": "Sales Quantity",
    "please_enter_quantity": "Please enter quantity",
    "amount_per_unit": "Amount per unit*",
    "please_enter_amount": "Please enter amount",
    "please_enter_amount_paid": "Please enter amount paid",
    "no_transactions_found": "No transactions found",
    "ltr": "Ltr",
    "kg": "kg",
    "usage_hours": "Usage Hours",
    "start_kilometer": "Start Kilometer",
    "end_kilometer": "End Kilometer",
    "tool_items": "Tool Items",
    "profile": "சுயவிவரம்",
    "no_profile_data_available": "சுயவிவரத் தகவல் கிடைக்கவில்லை",
    "logout": "வெளியேறு",
    "logout_confirmation": "வெளியேற விரும்புகிறீர்களா?",
  
    "current_plan": "Current Plan",
    "validity": "Validity",
    "start_date": "Start Date",
    "end_date": "End Date",
    "remaining_days": "Remaining Days",
    "explore_plans": "Explore Plans",
    "contact_information": "Contact Information",
    "company_details": "Company Details",
    "company_name": "Company Name",


    "select_market": "Select Market",
    "select_inventory_types": "Select Inventory Types",
    "loading_markets": "Loading Markets...",
  };
}
