class Tamil {
   static  Map<String, String> list = {
        'fuel': 'எரிபொருள்',
        'vehicle': 'வாகனம்',
        'choose_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
        "monthly_based_graph": "மாதாந்திர அடிப்படையிலான வரைபடம்",
        "sales": "விற்பனை",
        "expenses": "செலவுகள்",
        "no_finance_data": "நிதி தரவு இல்லை",
        "guidelines": "வழிகாட்டுதல்கள்",
        "view_all": "அனைத்தும்",
        "no_guidelines": "வழிகாட்டுதல்கள் இல்லை",
        "unable_to_open_content": "உள்ளடக்கத்தை திறக்க முடியவில்லை",
        "market_prices": "அருகிலுள்ள சந்தை விலைகள்",
        "no_data_available": "தரவு இல்லை",
        "error_message": "பிழை: {error}",
        "trending_crops": "பிரபலமான பயிர்கள்",
        "tasks": "பணிகள்",
        "no_tasks_available": "பணிகள் இல்லை",
        "widget_settings": "விட்ஜெட் அமைப்புகள்",
        "weather_payments": "வானிலை & பணம் செலுத்துதல்",
        "finance_graph": "நிதி வரைபடம்",
        "cancel": "ரத்து செய்",
        "save": "சேமி",
        "receivables": "பெறத்தக்கவை",
        "payables": "செலுத்த வேண்டியவை",
        "humidity_percentage": "ஈரப்பதம்: ",
        "currency_symbol": "₹",
      };
}