class Tamil {
  static Map<String, String> list = {
    'fuel': 'எரிபொருள்',
    'vehicle': 'வாகனம்',
    'choose_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    "monthly_based_graph": "மாதாந்திர அடிப்படையிலான வரைபடம்",
    "sales": "விற்பனை",
    "expenses": "செலவுகள்",
    "no_finance_data": "நிதி தரவு இல்லை",
    "guidelines": "வழிகாட்டுதல்கள்",
    "view_all": "அனைத்தும்",
    "no_guidelines": "வழிகாட்டுதல்கள் இல்லை",
    "unable_to_open_content": "உள்ளடக்கத்தை திறக்க முடியவில்லை",
    "market_prices": "அருகிலுள்ள சந்தை விலைகள்",
    "no_data_available": "தரவு இல்லை",
    "error_message": "பிழை: {error}",
    "trending_crops": "பிரபலமான பயிர்கள்",
    "tasks": "பணிகள்",
    "no_tasks_available": "பணிகள் இல்லை",
    "widget_settings": "விட்ஜெட் அமைப்புகள்",
    "weather_payments": "வானிலை & பணம் செலுத்துதல்",
    "finance_graph": "நிதி வரைபடம்",
    "cancel": "ரத்து செய்",
    "save": "சேமி",
    "receivables": "பெறத்தக்கவை",
    "payables": "செலுத்த வேண்டியவை",
    "humidity_percentage": "ஈரப்பதம்: ",
    "currency_symbol": "₹",

    "edit_task": "பணி திருத்து",
    "add_new_task": "புதிய பணி சேர்க்கவும்",
    "crop": "பழுத்தளி",
    "activity_type": "செயற்பாட்டின் வகை ",
    "schedule_date": "திட்டமிடல் தேதி",
    "recurring_task": "மறுபடி நிகழும் பணி",
    "daily": "தினசரி",
    "weekly": "வாராந்திர ",
    "monthly": "மாதாந்திர ",
    "mon": "திங்கள்",
    "tue": "செவ்வாய்",
    "wed": "புதன்",
    "thu": "வியாழன்",
    "fri": "வெள்ளி",
    "sat": "சனி",
    "sun": "ஞாயிறு",
    "schedule_end_date": "திட்டமிடல் நிறைவு தேதி",
    "not_selected": "தேர்ந்தெடுக்கப்படவில்லை",
    "please_add_end_date": "தயவு செய்து நிறைவு தேதியை சேர்க்கவும்",
    "description": "விளக்கம்",
    "update_task": "பணி புதுப்பிக்கவும்",
    "add_task": "பணி சேர்க்கவும்",
    "new_sales": "புதிய விற்பனை",
    "sales_amount": "விற்பனை தொகை",
    "total_sales_amount": "மொத்த விற்பனை தொகை",
    "customer": "வாடிக்கையாளர் *",
    "please_select_a_customer": "தயவு செய்து வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்",
    "vendor_customer": "வாடிக்கையாளர்",
    "date": "தேதி",
    "sales_quantity": "விற்பனை அளவு",
    "please_enter_quantity": "தயவு செய்து அளவை உள்ளிடவும்",
    "unit": "அலகு*",
    "amount_per_unit": "ஒரு அலகுக்கான தொகை*",
    "please_enter_amount": "தயவு செய்து தொகையை உள்ளிடவும்",
    "deductions": "விலக்கு",
    "deduction_amount": "விலக்கு தொகை",
    "amount_paid": "கட்டப்பட்ட தொகை*",
    "please_enter_amount_paid": "தயவு செய்து கட்டப்பட்ட தொகையை உள்ளிடவும்",
    "submit": "சமர்ப்பிக்கவும்",
    "add_deduction": "விலக்கு சேர்க்கவும்",
    "reason": "காரணம்*",
    "reason_for_deduction": "விலக்குக்கான காரணம்",
    "please_enter_a_reason": "தயவு செய்து காரணத்தை உள்ளிடவும்",
    "please_enter_deduction_amount": "தயவு செய்து விலக்கு தொகையை உள்ளிடவும்",
    "deduction_must_be_greater_than_0": "விலக்கு 0-இன் மேல் இருக்க வேண்டும்",
    "percentage_cannot_exceed_100": "சதவீதம் 100-ஐ கடக்க முடியாது",
    "no_documents_added": "எந்த ஆவணங்களும் சேர்க்கப்படவில்லை",
    "documents": "ஆவணங்கள்",
    "add_document": "ஆவணம் சேர்க்கவும்",
    "select_document_type": "ஆவண வகையைத் தேர்ந்தெடுக்கவும்",
    "enter_document_type": "ஆவண வகையை உள்ளிடவும்",
    "please_enter_a_document": "தயவு செய்து ஆவணத்தை உள்ளிடவும்",

    "sales_list": "விற்பனை பட்டியல்",
    "total_sales": "மொத்த விற்பனை",
    "week": "வாரம்",
    "month": "மாதம்",
    "year": "ஆண்டு",
    "sale_quantity": "விற்பனை அளவு",

    "add_new": "புதியவை சேர்க்கவும்",
    "purchase": "வாங்குதல்",
    "total_expenses": "மொத்த செலவுகள்",

    "30days": "30 நாட்கள்",

    "all": "எல்லாம்",
    "purchases": "வாங்குதல்கள்",
    "no_transactions_found": "பரிவர்த்தனைகள் காணப்படவில்லை",
    "no_inventory_data": "சரக்குத் தளவு தரவு இல்லை",
    "inventory": "சரக்குத் தளவு",

    "ltr": "லிட்டர்",
    "machinery": " இயந்திரம்",
    "tools": "கருவிகள்",
    "pesticides": "பருத்திக்கொல்லிகள்",
    "kg": "கிலோ",
    "fertilizers": " உரங்கள்",
    "seeds": "விதைகள்",
    "consumption": "செலவு",

    "inventory_type": "சரக்கு வகை",
    "required_field": "கட்டாயமான புலம்",
    "inventory_category": "சரக்கு வகைபாடு",
    "inventory_item": "சரக்கு பொருள்",
    "quantity": "அளவு",
    "usage_hours": "பயன்பாடு மணிநேரங்கள்",
    "start_kilometer": "துவக்கம் கிலோமீட்டர்",
    "end_kilometer": "முடிவு கிலோமீட்டர்",
    "tool_items": "கருவி பொருட்கள்",
    "profile": "சுயவிவரம்",
    "no_profile_data_available": "சுயவிவரத் தகவல் கிடைக்கவில்லை",
    "logout": "வெளியேறு",
    "logout_confirmation": "வெளியேற விரும்புகிறீர்களா?",
    "current_plan": "தற்போதைய திட்டம்",
    "validity": "சரிபார்ப்பு காலம்",
    "start_date": "தொடக்க தேதி",
    "end_date": "முடிவு தேதி",
    "remaining_days": "மீதமுள்ள நாட்கள்",
    "explore_plans": "திட்டங்களை ஆராய்க",
    "contact_information": "தொடர்பு தகவல்",
    "company_details": "நிறுவன விவரங்கள்",
    "company_name": "நிறுவன பெயர்",
    "tax_number": "வரி எண்",

    "both": "இரண்டும்",
    "vendor": "விற்பனையாளர்",


  "add_customer": "வாடிக்கையாளரைச் சேர்க்கவும்",
  "add_vendor": "விற்பனையாளரைச் சேர்க்கவும்",
  "add_both": "இரண்டையும் சேர்க்கவும்",
  "select_market": "சந்தையைத் தேர்ந்தெடுக்கவும்",

  "select_inventory_types": "சரக்கு வகைகளைத் தேர்ந்தெடுக்கவும்",
  "basic_info": "அடிப்படை தகவல்",
  "customer_name": "வாடிக்கையாளர் பெயர்",
  "vendor_name": "விற்பனையாளர் பெயர்",
  "mobile_number": "மொபைல் எண்",
  "invalid_phone": "தயவு செய்து செல்லுபடியாகும் தொலைபேசி எண்ணை உள்ளிடவும்",
  "email": "மின்னஞ்சல்",
  "invalid_email": "தயவு செய்து செல்லுபடியாகும் மின்னஞ்சல் முகவரியை உள்ளிடவும்",
  "shop_name": "கடை பெயர்",
  "business_name": "வியாபாரப் பெயர்",
  "location_info": "இடம் தகவல்",
  "address": "முகவரி",
  "pincode": "பின்கோடு",
  "pincode_length": "பின்கோடு 6 இலக்கங்கள் இருக்க வேண்டும்",
  "loading_markets": "சந்தைகள் ஏற்றப்படுகிறது...",
  "financial_info": "நிதி தகவல்",
  "gst_number": "GST எண்",


  };
}
