# Generated by Django 5.2.6 on 2025-09-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='{{ primary_color }}', max_length=7)),
                ('primary_color_rgb', models.CharField(default='107, 140, 40', max_length=20)),
                ('test_field', models.CharField(default='test', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='locations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managemarket',
            name='locations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='managenearbylocations',
            name='locations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
