# Generated by Django 5.2.6 on 2025-09-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_themesetting_generalsetting_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='locations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='weather_api_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
